from Products.CMFPlone import PloneMessageFactory as _
#_ = MessageFactory('plone')
dummy = _("FangAn")
dummy = _("ChuYang")
dummy = _("ChuYang1")
dummy = _("ChuYang2")
dummy = _("ShiYang")
dummy = _("ShiYang1")
dummy = _("ShiYang2")
dummy = _("ZhengYang")
dummy = _("ZhengYang1")
dummy = _("ZhengYang2")
dummy = _("DingXing")